import debug
file_name = "example.py"
#file_name = __name__ ###USE THIS if working with libraries

#Initialize empty array to store log data
log_array = []

#update the log array by setting it to the function debug.log(message, line, array)
#debug.get_line() will automatically put the line number
#pass in your current array
log_array = debug.log("Initializing Program", debug.get_line(), log_array)

try:
    RPL.servoWrite(0,1500)
    log_array = debug.log("stopping the motors", debug.get_line(), log_array)
except Exception as error:
    #error = the erorr message generated by python
    #it's good practice to pass in error as the message in debug.log
    log_array = debug.log(error, debug.get_line(), log_array)

log_array = debug.log("Program Completed", debug.get_line(), log_array)
#CALL THIS when the program finishes, (or whenever)
#debug.file_write saves log to logs directory
debug.file_write(log_array, file_name)
